services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole               #Hostname
    networks:
       pihole-network:
          ipv4_address: 172.24.0.10  #Change, to your pihole address in your subnet
    environment:
       TZ: 'America/Chicago'
       WEBPASSWORD: '12345678'
    # Volumes store your data between container upgrades
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
#    cap_add:
#      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
networks:
  pihole-network:
     name: local-network
